enable-delete-isolation-segments: false
enable-unassign-security-groups: false
enable-service-access: false
running-security-groups: []
staging-security-groups: []
shared-domains: {}
enable-remove-shared-domains: false
